import './globals.css'
import Sreads from '@/app/Sreads'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const runtime = 'edge'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={'sm:flex'}>
          <div className={'pl-12 pt-12 sm:pb-12 min-w-120'}>
            <Sreads />
          </div>
          <div className={'grow-0'}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
