import './globals.css'
import Threads from '@/app/Threads'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-4xl font-bold px-12 pt-12">
          なんでも実況E
        </h1>
        <div className={'sm:flex'}>
          <div className={'pl-12 pt-6 sm:pb-12 min-w-120'}>
            <Threads />
          </div>
          <div className={'grow-0'}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
