import './globals.css'
import { PostThread } from '@/app/PostThread'
import Threads from '@/app/Threads'
import { Loader2 } from 'lucide-react'
import { Inter } from 'next/font/google'
import { ReactNode, Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
                                      children
                                    }: {
  children: ReactNode
}) {
  return (
    <html lang="ja">
    <body className={inter.className}>
      <h1 className="text-4xl font-bold px-4 pt-4 sm:px-12 sm:pt-12">
        なんでも実況E
      </h1>
      <main className="sm:flex">
        <div className={'sm:pl-12 sm:pt-6 pl-4 pt-4 sm:pb-12 min-w-120 top-0 sticky h-full'}>
          <Suspense
            fallback={<div className={'grid place-content-center'}><Loader2 className={'animate-spin'} /></div>}
          >
            <Threads />
          </Suspense>
          {/*<PostThread />*/}
        </div>
        <div className={'grow-0'}>
          {children}
        </div>
      </main>
    </body>
    </html>
  )
}
